//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pm01_Astakhov_ConferenceEntities : DbContext
    {

        private static pm01_Astakhov_ConferenceEntities _context;

        public static pm01_Astakhov_ConferenceEntities GetContext()
        {
            if (_context == null)
                _context = new pm01_Astakhov_ConferenceEntities();
            return _context;
        }
        public pm01_Astakhov_ConferenceEntities()
            : base("name=pm01_Astakhov_ConferenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Jury> Jury { get; set; }
        public virtual DbSet<Moderators> Moderators { get; set; }
        public virtual DbSet<Organizers> Organizers { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
